title: Yongho Shin
description: Kernel/BSP/ML-Framework @Samsung Electornics
theme: just-the-docs

url: https://Tim-YonghoShin.github.io

aux_links:
  Template Repository: https://github.com/Tim-YonghoShin/Tim-YonghoShin.github.io

nav:
  - title: "Algorithm"
    url: /_posts/algorithm/
